"use client";
import Foot from "@/components/UIUX/Foot";
import Head from "@/components/UIUX/Head";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const url = usePathname();
  const urlPath = url != '/';

  return (
    <html lang="en">
      <body>
        <header>
          {urlPath && <Head />}
        </header>
        <main>{children}</main>
        <footer>
          {urlPath && <Foot />}
        </footer>

      </body>
    </html>

  );
}
